### ISSUE TITLE
Script doesn't work immediately on all books

### ISSUE THREAD

**Issue by Hannah-GBS** [SenorSmartyPants/ComicRack-MarkScannerPage#1]
I found this script recently and it seemed really useful so I ran it on my existing library and only got half a dozen books marked (as seen using the Pages marked deleted script). I knew I had more books that should have matched, so I found one, and after looking at its pages in the Info screen, and running the script on it again, it did mark the page Deleted.

Sure enough, I tried this on dozens of other books.
1. Run script on book, no result.
2. View the pages in the Info screen, visually confirming the have a scanner page.
3. Run the script on the book again, it marks the scanner page correctly.

Not sure if it's something I've done wrong with how I initially import books into my library or not, but it seemed super weird.

**Comment by SenorSmartyPants** [comment]
Ok, that was going to be my guess.

I think my code is assuming that CRW has already scanned the CBR/CBZ and generated the pages info. I'll have to see if there is a way to force a scan if there is no page info already in the database.

How are you importing into CRW?

**Comment by Hannah-GBS** [comment]
I just follow The Organizer workflow at the moment
![TeamViewer_U2SKnsnjms](https://user-images.githubusercontent.com/7504779/110840837-1c3a6f00-829d-11eb-9101-d2fba7523bb1.png)

**Comment by SenorSmartyPants** [comment]
Can you try a test for me.

Don't open the info window at anytime in this process.

Find a book that you know has a scanner page that you haven't tried the script on. One that you think will fail. Run the script on it, wait a minute. Check the pages marked deleted smart list to see if it shows up. If it doesn't run the script again, check the smart list.

**Comment by SenorSmartyPants** [comment]
I pushed a small update with a couple debug print statements. Please pull that and run with script console visible. see README.md on how to enable.

**Comment by Hannah-GBS** [comment]
> Find a book that you know has a scanner page that you haven't tried the script on. One that you think will fail. Run the script on it, wait a minute. Check the pages marked deleted smart list to see if it shows up. If it doesn't run the script again, check the smart list.

This didn't appear to do anything.

I will run the debug version now.

**Comment by Hannah-GBS** [comment]
`Main Series Black Panther V1998 #1 - The Client (1998/11/1) returned fewer than 5 pages. Not enough to find scanner page reliably.
Finished checking for scanner pages
`

**Comment by SenorSmartyPants** [comment]
I changed the out of that message slightly. Could you run it on the same book again?

Do you write the comicinfo.xml into your CBZs?

**Comment by Hannah-GBS** [comment]
Sure thing:
`Main Series Black Panther V1998 #1 - The Client (1998/11/1) returned fewer than 5 pages (1 pages reported). Not enough to find scanner page reliably.
Finished checking for scanner pages`

> Do you write the comicinfo.xml into your CBZs?

Yes, I do, and I can see that the only thing present in this book's XML under Pages is this
```
<Pages>
    <Page Type="FrontCover" ImageHeight="3056" ImageWidth="1988" Image="0"/>
</Pages>
```

**Comment by SenorSmartyPants** [comment]
This is pretty much what I thought was happening.

I'm not sure how to force CRW to update the page info, like it does when you manually look at the pages on the info dialog. Lack of documentation does not help.

Try converting/export the book to CBZ again. This will hopefully export a new full comicinfo.xml. You can then fix the rest of your library like that. Should be faster than opening every book if it works.

**Comment by Hannah-GBS** [comment]
Can confirm exporting to CBZ does work (as long as I remember to use my preset that maintains image names haha).

I can adjust my workflow to do that on all books rather than just CBLs in the future. Thanks!

**Comment by SenorSmartyPants** [comment]
Maintaining image names is definitely required. :)

If this fixes things for you please close this issue.

Glad you are finding the script useful.
