### ISSUE TITLE
Still Active? Not seeing it work in my CR....

### ISSUE THREAD

**Issue by shanezuspan** [SenorSmartyPants/ComicRack-MarkScannerPage#4]
Hi!

Ok, updated this post. Seems to be working once I converted to CBZ.  Selected about 100 and I did see the some of the files "update" so will poke around and see if it missed anything...

Would be cool to also be able to add images to a blacklist, figuring that image recognition is getting pretty darn good these days... or a blacklist of scanners which we can add to manually and add their scan pages to for recognition... like a "mark as dirty and add to... " option to add that image to a blacklist (or a blacklisted scanner name).

Thanks!

**Comment by SenorSmartyPants** [comment]
I won't be adding image recognition based tagging. As long as the comics are CBZ, comicrack has scanned the book and the files are still named as there were from the scanner (scanner image always has different name than the rest of the images) It should work.

**Comment by shanezuspan** [comment]
Ah! Ok, understood. I'll check if the image names are being retained on the ones I don't see...
